CREATE TABLE "role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" int NOT NULL,
  "name" varchar(25) NOT NULL,
  "email" varchar(40) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "admin" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users" int NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users" int NOT NULL
);

CREATE TABLE "student" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users" int NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "categorie" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "description" varchar(100) NOT NULL,
  "level" int NOT NULL,
  "teacher" int NOT NULL,
  "categorie" int NOT NULL
);

CREATE TABLE "item_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" int NOT NULL,
  "student" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" int NOT NULL,
  "url" varchar(200) NOT NULL,
  "course" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role") REFERENCES "role" ("id");

ALTER TABLE "admin" ADD FOREIGN KEY ("users") REFERENCES "users" ("id");

ALTER TABLE "teacher" ADD FOREIGN KEY ("users") REFERENCES "users" ("id");

ALTER TABLE "student" ADD FOREIGN KEY ("users") REFERENCES "users" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("level") REFERENCES "level" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("categorie") REFERENCES "categorie" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("teacher") REFERENCES "teacher" ("id");

ALTER TABLE "item_course" ADD FOREIGN KEY ("course") REFERENCES "course" ("id");

ALTER TABLE "item_course" ADD FOREIGN KEY ("student") REFERENCES "student" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course") REFERENCES "course" ("id");


INSERT INTO role (name) VALUES ('Student'), ('Teacher'),('Admin');

INSERT INTO users (name, email, password, age, role) VALUES ('Sebastian' ,'sebas@gmail.com', 'abcde', 18, 1), ('Patricia', 'paty@gmail.com', 'abcde', 17 , 2), ('Admin', 'admin@gmail.com', 'abcde', 25 , 3);

INSERT INTO admin (users) VALUES (3);

INSERT INTO teacher (users) VALUES (2);

INSERT INTO student (users) VALUES (1);

